[theme]
base = "dark"
primaryColor = "#00FFC6"               # Verde menta brillante
backgroundColor = "#0F1117"            # Gris oscuro / negro
secondaryBackgroundColor = "#1A1D26"   # Gris intermedio
textColor = "#FFFFFF"                  # Blanco puro
font = "sans serif"
